spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/lhub_dev?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
    username: lhub_owner  # modify username
    password: welcome1  # modify password

  jpa:
    hibernate:
      ddlAuto: update
    showSql: true

#logging:
 # level:
  #  org.springframework: DEBUG


